---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Install curl to fetch Nodesource script
      ansible.builtin.apt:
        name: curl
        state: present
        update_cache: yes

    - name: Run Nodesource setup script
      ansible.builtin.shell:
        cmd: "curl -fsSL {{ nodesource_setup_url }} | sudo -E bash -"
        creates: /etc/apt/sources.list.d/nodesource.list

    - name: Install Node.js package
      ansible.builtin.apt:
        name:
          - nodejs
        update_cache: yes
        state: present
