---
- hosts: all
  become: true

  tasks:
    - name: Install packages for Caddy repos
      ansible.builtin.apt:
        pkg:
          - debian-keyring
          - debian-archive-keyring
          - apt-transport-https
          - curl
        state: present
        update_cache: yes

    - name: Download Caddy Apt repository key
      ansible.builtin.get_url:
        url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
        dest: /etc/apt/trusted.gpg.d/caddy.asc

    - name: Set up Caddy Apt repository
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/etc/apt/trusted.gpg.d/caddy.asc] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main
        state: present

    - name: Install Caddy
      ansible.builtin.apt:
        name: caddy
        state: present
        update_cache: yes

    - name: Start Caddy webserver
      ansible.builtin.service:
        name: caddy
        state: started

    - name: UFW Firewall - Allow HTTP connections (port 80)
      community.general.ufw:
        rule: allow
        port: 80
        proto: tcp

    - name: UFW Firewall - Allow HTTPS connections (port 443)
      community.general.ufw:
        rule: allow
        port: 443
        proto: tcp
