---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Set up the wheel group
      ansible.builtin.group:
        name: wheel
        state: present

    - name: Allow the wheel group to have passwordless sudo
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        regexp: "^%wheel"
        line: "%wheel ALL=(ALL) NOPASSWD: ALL"
        validate: "/usr/sbin/visudo -cf %s"

    - name: Create a new regular user with sudo privileges
      ansible.builtin.user:
        name: "{{ create_user }}"
        state: present
        groups: wheel
        append: true
        create_home: true
        shell: /bin/bash

    - name: Set authorized key for remote user
      ansible.builtin.authorized_key:
        user: "{{ create_user }}"
        state: present
        key: "{{ copy_local_key }}"

    - name: Disable password authentication via SSH for root
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: "^#?PermitRootLogin"
        line: "PermitRootLogin prohibit-password"

    - name: Install initial required system packages
      ansible.builtin.apt:
        name: "{{ sys_packages }}"
        state: latest

    - name: UFW Firewall - Allow SSH connections
      community.general.ufw:
        rule: allow
        name: OpenSSH

    - name: UFW Firewall - Deny all other incoming traffic by default
      community.general.ufw:
        state: enabled
        policy: deny
        direction: incoming
